# Generated by Django 4.1.3 on 2022-12-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_portafolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="proyectos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni_1", models.CharField(default="", max_length=20)),
                ("foto_proy", models.CharField(default="", max_length=500)),
                ("titulo_proy", models.CharField(default="", max_length=200)),
                ("descrip_proy", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(default="", max_length=100)),
                ("apellidos", models.CharField(default="", max_length=100)),
                ("dni", models.CharField(default="", max_length=20)),
                ("usuarios", models.CharField(default="", max_length=150)),
                ("contraseña", models.CharField(default="", max_length=150)),
                ("fotoperfil", models.CharField(default="", max_length=500)),
                ("urlgithub", models.CharField(default="", max_length=500)),
            ],
        ),
    ]
